package database

// 2026-09-09 coder(lq): Keep explicit MySQL 5.6 DDL: no TEXT defaults, SERIAL, or CREATE INDEX IF NOT EXISTS.
const mysqlProxyRiskScoringDDL = `
CREATE TABLE IF NOT EXISTS proxy_risk_scoring_profiles (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL UNIQUE,
 provider VARCHAR(64) NOT NULL DEFAULT 'scamalytics',
 enabled BOOLEAN NOT NULL DEFAULT FALSE,
 priority INTEGER NOT NULL DEFAULT 0,
 base_url VARCHAR(512) NOT NULL DEFAULT '',
 access_token TEXT NULL,
 scamalytics_host VARCHAR(512) NOT NULL DEFAULT '',
 scamalytics_user TEXT NULL,
 scamalytics_key TEXT NULL,
 timeout_seconds INTEGER NOT NULL DEFAULT 8,
 concurrency INTEGER NOT NULL DEFAULT 3,
 request_delay_ms INTEGER NOT NULL DEFAULT 0,
 cache_ttl_seconds INTEGER NOT NULL DEFAULT 3600,
 max_checks_per_job INTEGER NOT NULL DEFAULT 0,
 daily_check_limit INTEGER NOT NULL DEFAULT 0,
 credit_reserve BIGINT NOT NULL DEFAULT 0,
 allow_force_refresh BOOLEAN NOT NULL DEFAULT FALSE,
 resolve_hostnames BOOLEAN NOT NULL DEFAULT FALSE,
 allow_private_targets BOOLEAN NOT NULL DEFAULT FALSE,
 docs_url VARCHAR(1024) NOT NULL DEFAULT '',
 tutorial_url VARCHAR(1024) NOT NULL DEFAULT '',
 daily_used_date VARCHAR(16) NOT NULL DEFAULT '',
 daily_used_count INTEGER NOT NULL DEFAULT 0,
 credits_remaining BIGINT NULL,
 credits_used BIGINT NULL,
 credit_reset_at DATETIME NULL,
 last_quota_checked_at DATETIME NULL,
 last_error TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_proxy_risk_profile_enabled(enabled, priority, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proxy_risk_score_snapshots (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 proxy_id BIGINT NOT NULL,
 profile_id BIGINT NOT NULL,
 provider VARCHAR(64) NOT NULL DEFAULT '',
 resolved_ip VARCHAR(64) NOT NULL DEFAULT '',
 score INTEGER NULL,
 risk_level VARCHAR(32) NOT NULL DEFAULT '',
 recommendation VARCHAR(32) NOT NULL DEFAULT '',
 proxy_type VARCHAR(32) NOT NULL DEFAULT '',
 is_vpn BOOLEAN NOT NULL DEFAULT FALSE,
 is_tor BOOLEAN NOT NULL DEFAULT FALSE,
 is_datacenter BOOLEAN NOT NULL DEFAULT FALSE,
 is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
 blacklist_sources TEXT NULL,
 isp VARCHAR(512) NOT NULL DEFAULT '',
 country VARCHAR(128) NOT NULL DEFAULT '',
 latency_ms INTEGER NOT NULL DEFAULT 0,
 status VARCHAR(32) NOT NULL DEFAULT 'error',
 error TEXT NULL,
 features_json MEDIUMTEXT NULL,
 raw_response_json MEDIUMTEXT NULL,
 checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at DATETIME NULL,
 INDEX idx_proxy_risk_snapshot_latest(proxy_id, profile_id, checked_at, id),
 INDEX idx_proxy_risk_snapshot_profile_time(profile_id, checked_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`
